name: thingspeak retrieval

on:
  schedule:
    - cron: '*/5 * * * *' # At 09:00 everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      #     pip3 install torch torchvision torchaudio
          
      - name: execute py script
        run: python thinkspeak_retrieve.py
